name: py3_nh
channels:
  - conda-forge
dependencies:
  - python=3.6
  - basemap
  - boule
  - cartopy
  - cartopy_offlinedata
  - gmt=6.0.0
  - harmonica
  - ipykernel
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - packaging
  - pandas
  - pip
  - pyproj
  - scikit-learn
  - scipy
  - sphinx
  - simplekml
  - utm
  - xarray
  - pip:
    - geophpy
    - sphinx_rtd_theme
    - git+https://github.com/GenericMappingTools/pygmt.git@dc178ed6d045275bf642023fe544d73154d5c987